### PR TITLE
Netlify Setup

### PR DESCRIPTION
**Pull request by ravivalluri**

### CODE REVIEW

**Comment by rackernexus** [comment]
Can one of the admins verify this patch?

**Comment by WilliamLoy** [comment]
build me

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 26 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-b2b27e2ed/docs/service-blocks/). valid for 14 days

**Pull request merged**
