### PR TITLE
fix contact email in readme

### PR DESCRIPTION
**Pull request by stephamon**
readme contact email was still the old one for the team

### CODE REVIEW

**Comment by edwardjrp** [comment]
build me

**Comment by edwardjrp** [comment]
build me

**Comment by edwardjrp** [comment]
build me

**Comment by rackernexus** [comment]
Build 8 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-2b93c26de/docs/service-blocks/). valid for 14 days

**Pull request merged**
